/* tslint:disable */
/* eslint-disable */
/**
 * Video Builder API
 * API for accepting frames and assembling video files with ffmpeg
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

